parameter_defaults:
  NetworkConfigWithAnsible: true
  ControllerNetworkConfigTemplate: /home/centos/tripleo/environments/master-upshift/nic-configs/controller.yaml
  ComputeNetworkConfigTemplate: /home/centos/tripleo/environments/master-upshift/nic-configs/compute.yaml
  CloudDomain: tripleodomain
  ControlPlaneMtu: 1400
  ExternalMtu: 1400
  InternalApiMtu: 1400
  StorageMtu: 1400
  StorageMgmtMtu: 1400
  TenantMtu: 1400
  EC2MetadataIp: 192.168.24.1
  ControlPlaneDefaultRoute: 192.168.1.1
  NtpServer:
    - clock.redhat.com
    - clock2.redhat.com
  DnsServers:
    - 10.11.5.19
    - 10.5.30.160
