parameter_defaults:
  ControllerNetworkConfigTemplate: /home/centos/tripleo/environments/master-upshift/nic-configs/controller_multiple_nics.j2
  ComputeNetworkConfigTemplate: /home/centos/tripleo/environments/master-upshift/nic-configs/compute_multiple_nics.j2
  SshFirewallAllowAll: true
  NeutronPublicInterface: eth1
  CloudDomain: tripleodomain
  ControlPlaneDefaultRoute: 192.168.1.1
  EC2MetadataIp: 192.168.24.2
  NtpServer:
    - clock.redhat.com
    - clock2.redhat.com
  DnsServers:
    - 10.11.5.19
    - 10.5.30.160
