---

- name: rhos-release
  hosts: all
  gather_facts: false
  tasks:
    - name: Run rhos-release
      raw: |
        sudo yum localinstall -y http://download.lab.bos.redhat.com/rcm-guest/puddles/OpenStack/rhos-release/rhos-release-latest.noarch.rpm
        sudo rhos-release rhel-8.0
        sudo dnf install -y python36
