#!/bin/bash

export CPU=1
export MEM=2048
export DISK=30
export ARCH=amd64
export MACS="52:54:00:dd:16:a1 52:54:00:bd:42:ba 52:54:00:63:59:db"
export NeutronPublicInterface=eth0
export OVERCLOUD_LIBVIRT_TYPE=qemu
export NETWORK_CIDR=10.0.0.0/8
export FLOATING_IP_START=192.0.2.45
export FLOATING_IP_END=192.0.2.64
export FLOATING_IP_CIDR=192.0.2.0/24

export COMPUTESCALE=1
export BLOCKSTORAGESCALE=1
export SWIFTSTORAGESCALE=0
