#!/bin/bash

export CPU=1
export MEM=2048
export DISK=20
export ARCH=amd64
export MACS="52:54:00:03:20:84 52:54:00:97:9f:68 52:54:00:62:a5:4e 52:54:00:e3:67:ca"
export NeutronPublicInterface=eth0
export OVERCLOUD_LIBVIRT_TYPE=qemu
export NETWORK_CIDR=10.0.0.0/8
export FLOATING_IP_START=192.0.2.45
export FLOATING_IP_END=192.0.2.64
export FLOATING_IP_CIDR=192.0.2.0/24

export COMPUTESCALE=1
export BLOCKSTORAGESCALE=1
export SWIFTSTORAGESCALE=0
