#!/bin/bash

DOMAIN=${1}
NETWORK=${2:-"default"}

function gimmieip {
    macaddr=$(virsh domiflist $DOMAIN | grep ${NETWORK} | awk '{print $5}')

    if [ -n "$macaddr" ]; then
        echo "MAC address $macaddr detected for $DOMAIN"
    else
        echo "No MAC address detected for $DOMAIN on $NETWORK"
        echo "Trying network brext..."
        macaddr=$(virsh domiflist $DOMAIN | grep brext | awk '{print $5}')
        if [ -n "$macaddr" ]; then
            echo "MAC address still not found."
            return
        fi
    fi

    ipaddr=$(ip n | grep $macaddr | awk '{print $1}' | tail -n 1)

    if [ -n "$ipaddr" ]; then
        echo "IP address $ipaddr detected for $DOMAIN"
    else
        echo "No IP address detected for $DOMAIN"
        return
    fi

    sudo sed -i "/\s$domain$/d" /etc/hosts 2>&1 > /dev/null
    echo -n "Writing $ipaddr for $DOMAIN to /etc/hosts..."
    sudo /bin/bash -c "echo $ipaddr $DOMAIN >> /etc/hosts"
    echo "Done."
}

gimmieip
