#!/bin/bash

set -eux

cd

sudo yum -y install http://repos.fedorapeople.org/repos/openstack-m/openstack-m/openstack-m-release-icehouse-1.noarch.rpm

sudo yum -y install instack-undercloud

cp tripleo/answers/instack.answers .

install-undercloud-packages
