#!/bin/bash

set -eux

export SUB_NODE_IPS=${SUB_NODE_IPS:-""}
export USER=${USER:-"centos"}

export SUDO_GROUP=${SUDO_GROUP:-"sudo"}

for ip in $SUB_NODE_IPS; do
	ssh-keygen -R $ip
	ssh-keyscan $ip >> ~/.ssh/known_hosts

	ssh -t root@$ip id $USER \|\| useradd -G $SUDO_GROUP $USER
	ssh -t root@$ip cp -r .ssh /home/$USER/
	ssh -t root@$ip chown -R $USER: /home/$USER
	ssh -t root@$ip iptables -D INPUT 1 || :
	ssh -t root@$ip 'which git || yum -y install git'
	ssh -t root@$ip ls tripleo-ci \|\| git clone https://git.openstack.org/openstack-infra/tripleo-ci
	ssh -t root@$ip ls tripleo \|\| git clone https://github.com/slagle/tripleo
	ssh -t root@$ip tripleo-ci/scripts/tripleo.sh --repo-setup
	ssh -t root@$ip rm -rf /usr/lib/python2.7/site-packages/requests
	ssh -t root@$ip yum -y install python-requests
	ssh -t root@$ip rm -rf /etc/puppet/modules/*
	ssh -t root@$ip yum -y remove puppet facter hiera
	ssh -t root@$ip yum -y install python-heat-agent*
done


