#!/bin/bash

set -eu

podman run \
    --name tripleo-dev \
    -d \
    quay.io/podman/stable \
    /bin/bash -c "useradd -G wheel,root stack; sed -i 's/# %wheel/%wheel/g' /etc/sudoers"

podman stop tripleo-dev
podman commit tripleo-dev tripleo-dev
podman rm -f tripleo-dev

podman run \
    --name tripleo-dev \
    -d \
    --privileged \
    --ulimit host \
    -u stack \
    -v /dev/fuse:/dev/fuse:rw \
    -e WORKING_DIR=/home/stack/openstack \
    -e VENV_DIR=/home/stack/openstack-venv \
    tripleo-dev \
    sleep infinity

podman exec -it -u stack tripleo-dev \
    /bin/bash -c "sudo chmod g+w -R /home/stack/openstack; mkdir -p /home/stack/openstack"

for r in python-tripleoclient tripleo-common tripleo-ansible; do
    podman cp ~/code/openstack/$r tripleo-dev:/home/stack/openstack
done

podman cp ~/code/openstack/tripleo/scripts/tripleo-dev-setup tripleo-dev:/home/stack/openstack

podman exec -it -u stack tripleo-dev /home/stack/openstack/tripleo-dev-setup

podman stop tripleo-dev
podman commit tripleo-dev tripleo-dev
podman rm -f tripleo-dev

echo "**********************************************"
echo "**********************************************"
echo "* Run the following to exec into tripleo-dev:"
echo "* (Optional) pass:"
echo "* -v \$CODE_DIR:/home/stack/openstack:z"
echo "* where \$CODE_DIR is the directoring containing"
echo "* tripleo git checkouts to use in the container"
echo
echo '
podman run \
    --name tripleo-dev \
    -d \
    --privileged \
    --ulimit host \
    -u stack \
    -v /dev/fuse:/dev/fuse:rw \
    -e WORKING_DIR=/home/stack/openstack \
    -e VENV_DIR=/home/stack/openstack-venv \
    tripleo-dev \
    sleep infinity
'
echo
echo "podman exec -it -u stack -w /home/stack tripleo-dev bash"
echo
echo "**********************************************"
echo "**********************************************"
