#!/bin/bash

set -eu

WORKING_DIR=${WORKING_DIR:-"$HOME/code/openstack"}
VENV_DIR=${VENV_DIR:-"$HOME/venvs/openstack"}
TRACE=${TRACE:-"0"}

if [ "$TRACE" -eq "1" ]; then
    set -x
fi

function instrpm {
    echo "* Checking for $1"
    if ! rpm -q --whatprovides $1; then
        echo "** Installing $1"
        sudo dnf -y install $1
    fi
}

function delrpm {
    echo "* Checking for $1"
    if rpm -q $1; then
        echo "** Uninstalling $1"
        sudo dnf erase -y $1
    fi
}

instrpm vim-enhanced
instrpm git
instrpm gcc
instrpm python3-devel
instrpm bash-completion
instrpm ansible
instrpm which
instrpm findutils
instrpm iproute

delrpm python3-pip

mkdir -p $WORKING_DIR
pushd $WORKING_DIR
if [ ! -d python-tripleoclient ]; then
    echo "* Cloning python-tripleoclient because it does not exist in $WORKING_DIR"
	git clone https://opendev.org/openstack/python-tripleoclient
fi
if [ ! -d tripleo-common ]; then
    echo "* Cloning tripleo-common because it does not exist in $WORKING_DIR"
	git clone https://opendev.org/openstack/tripleo-common
fi
if [ ! -d tripleo-ansible ]; then
    echo "* Cloning tripleo-ansible because it does not exist in $WORKING_DIR"
	git clone https://opendev.org/openstack/tripleo-ansible
fi
if [ ! -d tripleo-heat-templates ]; then
    echo "* Cloning tripleo-heat-templates because it does not exist in $WORKING_DIR"
	git clone https://opendev.org/openstack/tripleo-heat-templates
fi
popd

pushd ~
echo "* Checking for pip"
if [ ! -f /usr/local/bin/pip ]; then
	echo "** Downloading and installing pip"
    curl -L -O https://bootstrap.pypa.io/get-pip.py && sudo python3 get-pip.py
else
	echo "** Pip already installed"
fi
popd

if ! /usr/local/bin/pip show virtualenv; then
	echo "* Installing virtualenv"
    sudo /usr/local/bin/pip install virtualenv
fi
if ! /usr/local/bin/pip show epdb; then
	echo "* Installing epdb"
    sudo /usr/local/bin/pip install epdb
fi

echo "* Removing openstackclient"
sudo dnf erase -y python3-openstackclient --noautoremove

sudo rm -rf /usr/share/python-tripleoclient
sudo mkdir -p /usr/share/python-tripleoclient
sudo ln -s $WORKING_DIR/python-tripleoclient/templates /usr/share/python-tripleoclient/templates

sudo rm -rf /usr/share/tripleo-common
sudo mkdir -p /usr/share/tripleo-common
sudo ln -s $WORKING_DIR/tripleo-common/container-images /usr/share/tripleo-common
sudo ln -s $WORKING_DIR/tripleo-common/healthcheck /usr/share/tripleo-common
sudo ln -s $WORKING_DIR/tripleo-common/heat_docker_agent /usr/share/tripleo-common
sudo ln -s $WORKING_DIR/tripleo-common/image-yaml /usr/share/tripleo-common
sudo ln -s $WORKING_DIR/tripleo-common/sudoers /usr/share/tripleo-common

site_pkgs=$(python3 -c "import site; print(site.getsitepackages()[0])")
sudo mkdir -p $site_pkgs

sudo rm -rf $site_pkgs/tripleoclient
sudo ln -s $WORKING_DIR/python-tripleoclient/tripleoclient $site_pkgs/tripleoclient
pushd $WORKING_DIR/python-tripleoclient
rm -rf build
python3 setup.py build
popd
echo $WORKING_DIR/python-tripleoclient | sudo tee $site_pkgs/python-tripleoclient.egg-link
sudo rm -rf $site_pkgs/python_tripleoclient.egg-info
sudo ln -s $WORKING_DIR/python-tripleoclient/python_tripleoclient.egg-info $site_pkgs/

sudo rm -rf $site_pkgs/tripleo_common
sudo ln -s $WORKING_DIR/tripleo-common/tripleo_common $site_pkgs/tripleo_common
pushd $WORKING_DIR/tripleo-common
rm -rf build
python3 setup.py build
popd
echo $WORKING_DIR/tripleo-common | sudo tee $site_pkgs/tripleo-common.egg-link
sudo rm -rf $site_pkgs/tripleo_common.egg-info
sudo ln -s $WORKING_DIR/tripleo-common/tripleo_common.egg-info $site_pkgs/

sudo rm -rf /usr/share/openstack-tripleo-heat-templates
sudo ln -s $WORKING_DIR/tripleo-heat-templates /usr/share/openstack-tripleo-heat-templates

echo "* Symlinking ansible playbooks..."
sudo rm -rf /usr/share/ansible/tripleo-playbooks
sudo mkdir -p /usr/share/ansible
sudo ln -sf $WORKING_DIR/tripleo-ansible/tripleo_ansible/playbooks /usr/share/ansible/tripleo-playbooks

echo "* Symlinking ansible roles..."
sudo mkdir -p /usr/share/ansible/roles
for r in $WORKING_DIR/tripleo-ansible/tripleo_ansible/roles/*; do
    echo "** Symlinking /usr/share/ansible/roles/$(basename $r)"
    sudo rm -rf /usr/share/ansible/roles/$(basename $r)
    sudo ln -sf $r /usr/share/ansible/roles/
done

echo "* Symlinking ansible plugins..."
sudo mkdir -p /usr/share/ansible/plugins
for d in $WORKING_DIR/tripleo-ansible/tripleo_ansible/ansible_plugins/*; do
    sudo mkdir -p /usr/share/ansible/plugins/$(basename $d)
    for p in $d/*; do
        echo "** Symlinking /usr/share/ansible/plugins/$(basename $d)/$(basename $p)"
        sudo rm -rf /usr/share/ansible/plugins/$(basename $d)/$(basename $p)
        sudo ln -sf $p /usr/share/ansible/plugins/$(basename $d)/
    done
done

echo "* Symlinking ansible.module_utils.tripleo_common_utils..."
ansible_path=$(python -c "import ansible; print(ansible.__path__[0])")
sudo ln -s -f $WORKING_DIR/tripleo-ansible/tripleo_ansible/ansible_plugins/module_utils/tripleo_common_utils.py $ansible_path/module_utils/

if [ ! -d $VENV_DIR ]; then
    echo "* Creating $VENV_DIR"
    mkdir -p $VENV_DIR
    virtualenv --system-site-packages $VENV_DIR
    echo "** pip installing fixtures/greenlet for deps"
    $VENV_DIR/bin/pip install fixtures greenlet
    echo "** pip installing openstackclient"
    $VENV_DIR/bin/pip install openstackclient
    echo "** pip installing tripleoclient requirements"
    $VENV_DIR/bin/pip install -r $WORKING_DIR/python-tripleoclient/requirements.txt
    echo "** pip installing tripleo-common requirements"
    $VENV_DIR/bin/pip install -r $WORKING_DIR/tripleo-common/requirements.txt
fi


echo "** Symlinking /usr/bin/openstack"
sudo ln -sf $VENV_DIR/bin/openstack /usr/bin/

echo "* Creating $VENV_DIR/share/tripleo-common"
sudo rm -rf $VENV_DIR/share/tripleo-common
sudo mkdir -p $VENV_DIR/share/tripleo-common
echo "** Symlinking $VENV_DIR/share/tripleo-common/container-images"
sudo ln -s $WORKING_DIR/tripleo-common/container-images $VENV_DIR/share/tripleo-common
echo "** Symlinking $VENV_DIR/share/tripleo-common/healthcheck"
sudo ln -s $WORKING_DIR/tripleo-common/healthcheck $VENV_DIR/share/tripleo-common
echo "** Symlinking $VENV_DIR/share/tripleo-common/heat_docker_agent"
sudo ln -s $WORKING_DIR/tripleo-common/heat_docker_agent $VENV_DIR/share/tripleo-common
echo "** Symlinking $VENV_DIR/share/tripleo-common/image-yaml"
sudo ln -s $WORKING_DIR/tripleo-common/image-yaml $VENV_DIR/share/tripleo-common
echo "** Symlinking $VENV_DIR/share/tripleo-common/sudoers"
sudo ln -s $WORKING_DIR/tripleo-common/sudoers $VENV_DIR/share/tripleo-common

if [ ! -f /etc/bash_completion.d/openstack ]; then
    echo "* Running openstack complete"
    $VENV_DIR/bin/openstack complete | grep -v osc_lib | sudo tee /etc/bash_completion.d/openstack
    source /etc/bash_completion.d/openstack
    source /etc/profile.d/bash_completion.sh
fi

echo "* Backing up and removing ~/tripleo-heat-templates"
if [ -d ~/tripleo-heat-templates ]; then
    mv ~/tripleo-heat-templates ~/tripleo-heat-templates.save
    rm -rf ~/tripleo-heat-templates
fi
echo "* Symlinking ~/tripleo-heat-templates to $WORKING_DIR/tripleo-heat-templates"
ln -s -f $WORKING_DIR/tripleo-heat-templates ~/tripleo-heat-templates

echo "DONE."
