resource_registry:
  OS::TripleO::Controller::Net::SoftwareConfig: ../../../tripleo-heat-templates/net-config-static-bridge.yaml

parameter_defaults:
  EC2MetadataIp: 192.168.24.1
  ControlPlaneDefaultRoute: 192.168.24.1
  NtpServer:
    - clock.redhat.com
    - clock2.redhat.com
  DnsServers:
    - 192.168.1.12
    - 192.168.1.11
