resource_registry:
  OS::TripleO::Controller::Net::SoftwareConfig: ../../../tripleo-heat-templates/network/config/single-nic-vlans/controller.yaml
  OS::TripleO::DistributedComputeHCI::Net::SoftwareConfig: ../../../tripleo-heat-templates/network/config/single-nic-vlans/controller.yaml

parameter_defaults:
  EC2MetadataIp: 192.168.24.1
  ControlPlaneDefaultRoute: 192.168.1.1
  NtpServer:
    - clock.redhat.com
    - clock2.redhat.com
  DnsServers:
    - 192.168.1.12
    - 192.168.1.11
