resource_registry:
  OS::TripleO::Controller::Net::SoftwareConfig: /home/cloud-user/tripleo/environments/osp16-upshift/multiple-nics.yaml
  OS::TripleO::DistributedComputeHCI::Net::SoftwareConfig: /home/cloud-user/tripleo/environments/osp16-upshift/multiple-nics.yaml

parameter_defaults:
  EC2MetadataIp: 192.168.24.1
  ControlPlaneDefaultRoute: 192.168.1.1
  NtpServer:
    - clock.redhat.com
    - clock2.redhat.com
  DnsServers:
    - 10.11.5.19
    - 10.5.30.160
    - 192.168.1.12
    - 192.168.1.11

  ControllerIPs:
    storage:
      - 172.16.1.10
    external:
      - 10.0.0.10
    internal_api:
      - 172.16.2.10
    storage_mgmt:
      - 172.16.3.10
    tenant:
      - 172.16.0.10
    management:
      - 192.168.1.22

  InternalApiVirtualFixedIPs:
    - ip_address: 172.16.2.100

  StorageMgmtVirtualFixedIPs:
    - ip_address: 172.16.3.100

  StorageVirtualFixedIPs:
    - ip_address: 172.16.1.100

  ExternalVirtualFixedIPs:
    - ip_address: 10.0.0.100

