resource_registry:
  OS::TripleO::Controller::Net::SoftwareConfig: /home/cloud-user/tripleo/environments/osp16-upshift/multiple-nics.yaml
  OS::TripleO::DistributedComputeHCI::Net::SoftwareConfig: /home/cloud-user/tripleo/environments/osp16-upshift/multiple-nics.yaml

parameter_defaults:
  EC2MetadataIp: 192.168.24.1
  ControlPlaneDefaultRoute: 192.168.1.1
  NtpServer:
    - clock.redhat.com
    - clock2.redhat.com
  DnsServers:
    - 192.168.1.12
    - 192.168.1.11
