parameter_defaults:
  ComputeCount: 3
  ComputeHostnameFormat: '%stackname%-compute-%index%'
  ControllerCount: 3
  ControllerHostnameFormat: '%stackname%-controller-%index%'
  DeployedServerPortMap:
    master-compute-0-ctlplane:
      fixed_ips:
      - ip_address: 192.168.24.110
    master-compute-1-ctlplane:
      fixed_ips:
      - ip_address: 192.168.24.111
    master-compute-2-ctlplane:
      fixed_ips:
      - ip_address: 192.168.24.112
    master-controller-0-ctlplane:
      fixed_ips:
      - ip_address: 192.168.24.10
    master-controller-1-ctlplane:
      fixed_ips:
      - ip_address: 192.168.24.11
    master-controller-2-ctlplane:
      fixed_ips:
      - ip_address: 192.168.24.12
    control_virtual_ip:
      fixed_ips:
      - ip_address: 192.168.24.100
    external_virtual_ip:
      fixed_ips:
      - ip_address: 10.0.0.100
    internal_api_virtual_ip:
      fixed_ips:
      - ip_address: 172.16.2.100
    storage_virtual_ip:
      fixed_ips:
      - ip_address: 172.16.1.100
    storage_mgmt_virtual_ip:
      fixed_ips:
      - ip_address: 172.16.3.100
    redis_virtual_ip:
      fixed_ips:
      - ip_address: 172.16.2.101
    ovn_dbs_virtual_ip:
      fixed_ips:
      - ip_address: 172.16.2.102
  HostnameMap:
    overcloud-compute-0: master-compute-0
    overcloud-compute-1: master-compute-1
    overcloud-compute-2: master-compute-2
    overcloud-controller-0: master-controller-0
    overcloud-controller-1: master-controller-1
    overcloud-controller-2: master-controller-2
  NodePortMap:
    master-compute-0:
      ctlplane:
        ip_address: 192.168.24.110
        ip_address_uri: 192.168.24.110
        ip_subnet: 192.168.24.110/24
      external:
        ip_address: 10.0.0.110
        ip_address_uri: 10.0.0.110
        ip_subnet: 10.0.0.110/24
      internal_api:
        ip_address: 172.16.2.110
        ip_address_uri: 172.16.2.110
        ip_subnet: 172.16.2.110/24
      management:
        ip_address: 192.168.1.110
        ip_address_uri: 192.168.1.110
        ip_subnet: 192.168.1.110/24
      storage:
        ip_address: 172.16.1.110
        ip_address_uri: 172.16.1.110
        ip_subnet: 172.16.1.110/24
      storage_mgmt:
        ip_address: 172.16.3.110
        ip_address_uri: 172.16.3.110
        ip_subnet: 172.16.3.110/24
      tenant:
        ip_address: 172.16.0.110
        ip_address_uri: 172.16.0.110
        ip_subnet: 172.16.0.110/24
    master-compute-1:
      ctlplane:
        ip_address: 192.168.24.111
        ip_address_uri: 192.168.24.111
        ip_subnet: 192.168.24.111/24
      external:
        ip_address: 10.0.0.111
        ip_address_uri: 10.0.0.111
        ip_subnet: 10.0.0.111/24
      internal_api:
        ip_address: 172.16.2.111
        ip_address_uri: 172.16.2.111
        ip_subnet: 172.16.2.111/24
      management:
        ip_address: 192.168.1.111
        ip_address_uri: 192.168.1.111
        ip_subnet: 192.168.1.111/24
      storage:
        ip_address: 172.16.1.111
        ip_address_uri: 172.16.1.111
        ip_subnet: 172.16.1.111/24
      storage_mgmt:
        ip_address: 172.16.3.111
        ip_address_uri: 172.16.3.111
        ip_subnet: 172.16.3.111/24
      tenant:
        ip_address: 172.16.0.111
        ip_address_uri: 172.16.0.111
        ip_subnet: 172.16.0.111/24
    master-compute-2:
      ctlplane:
        ip_address: 192.168.24.112
        ip_address_uri: 192.168.24.112
        ip_subnet: 192.168.24.112/24
      external:
        ip_address: 10.0.0.112
        ip_address_uri: 10.0.0.112
        ip_subnet: 10.0.0.112/24
      internal_api:
        ip_address: 172.16.2.112
        ip_address_uri: 172.16.2.112
        ip_subnet: 172.16.2.112/24
      management:
        ip_address: 192.168.1.112
        ip_address_uri: 192.168.1.112
        ip_subnet: 192.168.1.112/24
      storage:
        ip_address: 172.16.1.112
        ip_address_uri: 172.16.1.112
        ip_subnet: 172.16.1.112/24
      storage_mgmt:
        ip_address: 172.16.3.112
        ip_address_uri: 172.16.3.112
        ip_subnet: 172.16.3.112/24
      tenant:
        ip_address: 172.16.0.112
        ip_address_uri: 172.16.0.112
        ip_subnet: 172.16.0.112/24
    master-controller-0:
      ctlplane:
        ip_address: 192.168.24.10
        ip_address_uri: 192.168.24.10
        ip_subnet: 192.168.24.10/24
      external:
        ip_address: 10.0.0.10
        ip_address_uri: 10.0.0.10
        ip_subnet: 10.0.0.10/24
      internal_api:
        ip_address: 172.16.2.10
        ip_address_uri: 172.16.2.10
        ip_subnet: 172.16.2.10/24
      management:
        ip_address: 192.168.1.10
        ip_address_uri: 192.168.1.10
        ip_subnet: 192.168.1.10/24
      storage:
        ip_address: 172.16.1.10
        ip_address_uri: 172.16.1.10
        ip_subnet: 172.16.1.10/24
      storage_mgmt:
        ip_address: 172.16.3.10
        ip_address_uri: 172.16.3.10
        ip_subnet: 172.16.3.10/24
      tenant:
        ip_address: 172.16.0.10
        ip_address_uri: 172.16.0.10
        ip_subnet: 172.16.0.10/24
    master-controller-1:
      ctlplane:
        ip_address: 192.168.24.11
        ip_address_uri: 192.168.24.11
        ip_subnet: 192.168.24.11/24
      external:
        ip_address: 10.0.0.11
        ip_address_uri: 10.0.0.11
        ip_subnet: 10.0.0.11/24
      internal_api:
        ip_address: 172.16.2.11
        ip_address_uri: 172.16.2.11
        ip_subnet: 172.16.2.11/24
      management:
        ip_address: 192.168.1.11
        ip_address_uri: 192.168.1.11
        ip_subnet: 192.168.1.11/24
      storage:
        ip_address: 172.16.1.11
        ip_address_uri: 172.16.1.11
        ip_subnet: 172.16.1.11/24
      storage_mgmt:
        ip_address: 172.16.3.11
        ip_address_uri: 172.16.3.11
        ip_subnet: 172.16.3.11/24
      tenant:
        ip_address: 172.16.0.11
        ip_address_uri: 172.16.0.11
        ip_subnet: 172.16.0.11/24
    master-controller-2:
      ctlplane:
        ip_address: 192.168.24.12
        ip_address_uri: 192.168.24.12
        ip_subnet: 192.168.24.12/24
      external:
        ip_address: 10.0.0.12
        ip_address_uri: 10.0.0.12
        ip_subnet: 10.0.0.12/24
      internal_api:
        ip_address: 172.16.2.12
        ip_address_uri: 172.16.2.12
        ip_subnet: 172.16.2.12/24
      management:
        ip_address: 192.168.1.12
        ip_address_uri: 192.168.1.12
        ip_subnet: 192.168.1.12/24
      storage:
        ip_address: 172.16.1.12
        ip_address_uri: 172.16.1.12
        ip_subnet: 172.16.1.12/24
      storage_mgmt:
        ip_address: 172.16.3.12
        ip_address_uri: 172.16.3.12
        ip_subnet: 172.16.3.12/24
      tenant:
        ip_address: 172.16.0.12
        ip_address_uri: 172.16.0.12
        ip_subnet: 172.16.0.12/24
resource_registry:
  OS::TripleO::Compute::Ports::ExternalPort: /home/stack/tripleo-heat-templates/network/ports/deployed_external.yaml
  OS::TripleO::Compute::Ports::InternalApiPort: /home/stack/tripleo-heat-templates/network/ports/deployed_internal_api.yaml
  OS::TripleO::Compute::Ports::ManagementPort: /home/stack/tripleo-heat-templates/network/ports/deployed_management.yaml
  OS::TripleO::Compute::Ports::StorageMgmtPort: /home/stack/tripleo-heat-templates/network/ports/deployed_storage_mgmt.yaml
  OS::TripleO::Compute::Ports::StoragePort: /home/stack/tripleo-heat-templates/network/ports/deployed_storage.yaml
  OS::TripleO::Compute::Ports::TenantPort: /home/stack/tripleo-heat-templates/network/ports/deployed_tenant.yaml
  OS::TripleO::Controller::Ports::ExternalPort: /home/stack/tripleo-heat-templates/network/ports/deployed_external.yaml
  OS::TripleO::Controller::Ports::InternalApiPort: /home/stack/tripleo-heat-templates/network/ports/deployed_internal_api.yaml
  OS::TripleO::Controller::Ports::ManagementPort: /home/stack/tripleo-heat-templates/network/ports/deployed_management.yaml
  OS::TripleO::Controller::Ports::StorageMgmtPort: /home/stack/tripleo-heat-templates/network/ports/deployed_storage_mgmt.yaml
  OS::TripleO::Controller::Ports::StoragePort: /home/stack/tripleo-heat-templates/network/ports/deployed_storage.yaml
  OS::TripleO::Controller::Ports::TenantPort: /home/stack/tripleo-heat-templates/network/ports/deployed_tenant.yaml
  OS::TripleO::DeployedServer::ControlPlanePort: /home/stack/tripleo-heat-templates/deployed-server/deployed-neutron-port.yaml

  OS::TripleO::Network::Ports::ExternalVipPort: /home/stack/tripleo-heat-templates/network/ports/vip.yaml
  OS::TripleO::Network::Ports::InternalApiVipPort: /home/stack/tripleo-heat-templates/network/ports/vip.yaml
  OS::TripleO::Network::Ports::StorageVipPort: /home/stack/tripleo-heat-templates/network/ports/vip.yaml
  OS::TripleO::Network::Ports::StorageMgmtVipPort: /home/stack/tripleo-heat-templates/network/ports/vip.yaml
  OS::TripleO::Network::Ports::RedisVipPort: /home/stack/tripleo-heat-templates/network/ports/vip.yaml
  OS::TripleO::Network::Ports::OVNDBsVipPort: /home/stack/tripleo-heat-templates/network/ports/vip.yaml
